language: php
sudo: false

env:
  matrix:
    - COMPOSER_UPDATE=false
    - COMPOSER_UPDATE=true

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  exclude:
    - php: 5.5
      env: COMPOSER_UPDATE=false
    - php: 5.6
      env: COMPOSER_UPDATE=false
    - php: 7.0
      env: COMPOSER_UPDATE=false
    - php: 7.1
      env: COMPOSER_UPDATE=true
    - php: 7.2
      env: COMPOSER_UPDATE=true
    - php: nightly
      env: COMPOSER_UPDATE=true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - if [ $COMPOSER_UPDATE == "true" ]; then composer update; else composer install --prefer-dist --no-progress --no-interaction; fi
  - composer install --prefer-dist --no-progress --no-interaction

script:
  - vendor/bin/robo check:codestyle
